/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vscode.java.debug.bug;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.Mockito.spy;

import org.junit.jupiter.api.Test;

public class AppTest {
  @Test
  public void testAppHasAGreeting() {
    App classUnderTest = spy(new App());
    String greeting = classUnderTest.getGreeting();
    assertNotNull(greeting, "app should have a greeting");
  }
}
